language: bash

env:
  global:
  - IMAGE_NAME=${DOCKER_USERNAME}/nginx-custom

matrix:
  include:
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.16.0
    - REPO_REV=release-1.16.0
    - MODULES_LABEL=base
    - MODULES=""
    - TERA_VERSION=v0.1.1
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.16.0
    - REPO_REV=release-1.16.0
    - MODULES_LABEL=base
    - MODULES=""
    - TERA_VERSION=
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.16.0
    - REPO_REV=release-1.16.0
    - MODULES_LABEL=full
    - MODULES="--with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module"
    - TERA_VERSION=v0.1.1
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.16.0
    - REPO_REV=release-1.16.0
    - MODULES_LABEL=full
    - MODULES="--with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module"
    - TERA_VERSION=
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.16.0
    - REPO_REV=release-1.16.0
    - MODULES_LABEL=standard
    - MODULES="--with-http_ssl_module --with-http_sub_module --with-http_gunzip_module --with-http_gzip_static_module"
    - TERA_VERSION=v0.1.1
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.16.0
    - REPO_REV=release-1.16.0
    - MODULES_LABEL=standard
    - MODULES="--with-http_ssl_module --with-http_sub_module --with-http_gunzip_module --with-http_gzip_static_module"
    - TERA_VERSION=
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.15.12
    - REPO_REV=release-1.15.12
    - MODULES_LABEL=base
    - MODULES=""
    - TERA_VERSION=v0.1.1
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.15.12
    - REPO_REV=release-1.15.12
    - MODULES_LABEL=base
    - MODULES=""
    - TERA_VERSION=
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.15.12
    - REPO_REV=release-1.15.12
    - MODULES_LABEL=full
    - MODULES="--with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module"
    - TERA_VERSION=v0.1.1
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.15.12
    - REPO_REV=release-1.15.12
    - MODULES_LABEL=full
    - MODULES="--with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module"
    - TERA_VERSION=
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.15.12
    - REPO_REV=release-1.15.12
    - MODULES_LABEL=standard
    - MODULES="--with-http_ssl_module --with-http_sub_module --with-http_gunzip_module --with-http_gzip_static_module"
    - TERA_VERSION=v0.1.1
  - services: docker
    env:
    - REPO_GIT_URL=https://github.com/nginx/nginx.git
    - REPO_VER=1.15.12
    - REPO_REV=release-1.15.12
    - MODULES_LABEL=standard
    - MODULES="--with-http_ssl_module --with-http_sub_module --with-http_gunzip_module --with-http_gzip_static_module"
    - TERA_VERSION=
  
script:
- set -e
- docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
- |-
  if [ -z "${TERA_VERSION}" ]; then
    TERA_TAG=""
  else
    TERA_TAG="_with-tera"
  fi
- TAG_NAME="${REPO_VER}_${MODULES_LABEL}${TERA_TAG}"
- FULL_IMAGE_NAME="${IMAGE_NAME}:${TAG_NAME}"
- |-
  docker build . -t ${FULL_IMAGE_NAME} \
    --build-arg REPO_GIT_URL="${REPO_GIT_URL}" \
    --build-arg REPO_REV="${REPO_REV}" \
    --build-arg MODULES="${MODULES}" \
    --build-arg TERA_VERSION="${TERA_VERSION}" \
    ;
# Just push, doesn't matter if it's TRAVIS_PULL_REQUEST false/true
- docker push ${FULL_IMAGE_NAME};

branches:
  only:
  - master
